apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-lab
  namespace: data-lab
rules:
  - apiGroups: ["","batch"]
    resources: ["pods",
                "pods/log",
                "events",
                "services",
                "jobs",
                "jobs/status"]
    verbs: ["delete",
            "create",
            "get",
            "watch",
            "list",
            "endpoints",
            "patch",
            "events"]
